services:
  postgres:
    image: postgres:16
    container_name: infra-postgres-1
    environment:
      POSTGRES_USER: ndai
      POSTGRES_PASSWORD: ndai
      POSTGRES_DB: ndai
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ndai -d ndai"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio:
    image: minio/minio:latest
    container_name: infra-minio-1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: infra-zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: infra-kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # INTERNAL pour Spark/API dans Docker, EXTERNAL pour ton Mac
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://infra-kafka-1:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  metabase:
    image: metabase/metabase:latest
    container_name: infra-metabase-1
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  api-feedback:
    build:
      context: ../services/api-feedback
    container_name: infra-api-feedback-1
    environment:
      API_KEY: ${API_KEY}
      BASIC_USER: ${BASIC_USER}
      BASIC_PASS: ${BASIC_PASS}
      KAFKA_BOOTSTRAP: infra-kafka-1:9092
      KAFKA_TOPIC: feedback.created
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio12345
      S3_BUCKET_RAW: raw-feedback
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - kafka
      - minio